"""
The one place a SQLAlchemy Engine (and Session factory) gets constructed.
The API, agent, and poller all import from here rather than each opening
their own connection — that's what "shared data-access module" means in
practice.

This project uses the SQLAlchemy ORM (models in jobsentinel.db.models,
migrations autogenerated from them) — but data-access functions like
jobsentinel.db.jobs.get_job still hand callers plain dicts, not live ORM
objects, so nothing outside this module needs to think about session
lifetimes. get_engine() also stays useful on its own for Core-level
statements (see jobsentinel.db.jobs.upsert_jobs) where the ORM has no
native equivalent, like a real Postgres upsert.
"""

from functools import lru_cache

from sqlalchemy import Engine, create_engine
from sqlalchemy.orm import Session, sessionmaker

from jobsentinel.config import get_settings


@lru_cache
def get_engine() -> Engine:
    """
    Cached so the whole process shares one Engine (and therefore one
    connection pool) instead of every caller opening a fresh pool of its own.

    A SQLAlchemy Engine already *is* a connection pool — pool_pre_ping=True
    additionally checks a connection is still alive before handing it out,
    which matters for long-lived Lambda execution environments where the
    Postgres side may have closed an idle connection between invocations.
    """
    return create_engine(get_settings().database_url, pool_pre_ping=True)


@lru_cache
def get_session_factory() -> sessionmaker[Session]:
    """
    A callable that produces new ORM Sessions bound to the shared engine.

    Cached for the same reason get_engine() is: build this once, reuse it,
    rather than every caller re-deriving it from get_engine(). Usage:

        with get_session_factory()() as session:
            ...

    (or wrap that in a `with Session(get_engine()) as session:` directly,
    as jobsentinel.db.jobs.get_job does — both are equivalent; this factory
    exists for callers that want the sessionmaker itself, e.g. to pass into
    FastAPI's dependency-injection system in a later slice.)
    """
    return sessionmaker(bind=get_engine())
