"""create user_companies table

Revision ID: a415eab45216
Revises: 00f1e70971b1
Create Date: 2026-10-05 12:52:33.643024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a415eab45216'
down_revision: Union[str, Sequence[str], None] = '00f1e70971b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_companies',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_user_companies_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    op.create_index(op.f('ix_user_companies_company_id'), 'user_companies', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_companies_company_id'), table_name='user_companies')
    op.drop_table('user_companies')
    # ### end Alembic commands ###
