"""index jobs company_id

Revision ID: ec666d8a6a0d
Revises: a415eab45216
Create Date: 2026-10-06 11:42:11.905041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec666d8a6a0d'
down_revision: Union[str, Sequence[str], None] = 'a415eab45216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    # ### end Alembic commands ###
